### ISSUE TITLE
vj_npcspawner_sv_create exploits

### ISSUE THREAD

**Issue by xLomble77** [DrVrej/VJ-Base#115]
In the title, the net "vj_npcspawner_sv_create" is exploitable.

**Comment by DrVrej** [comment]
Thank you for the concern. In order to have this net message to run the player needs to actively have the tool gun out with VJ NPC spawner selected. Now I don't know about you but I can't think of a situation where the server owners are letting regular members have a tool gun and the ability to use the NPC spawner without restricting it to admins. If you are allowing them to even have access to the NPC spawner tool, then you have much bigger issues at hand. If you think I have missed a case then please let me know, otherwise this isn't exploitable.
