### ISSUE TITLE
Google Login Phishing Menu

### ISSUE THREAD

**Issue by ZombieWars** [DrVrej/VJ-Base#117]
Hello, are you aware if a server is using the VJBASE addon and a player joins without being subscribed to it they get prompted a google login menu when joining?? this is a major redflag because once you type stuff in nothing happens -- I pinpointed it to this addon so before you say otherwise.

**Comment by ZombieWars** [comment]
also tested github version same thing

**Comment by ZombieWars** [comment]
![image](https://github.com/DrVrej/VJ-Base/assets/169955667/3ccc446a-7e81-45f7-b146-1010a71d27e1)

**Comment by ZombieWars** [comment]
Please tell me why you even have this on your addon where if someone is not subbed to the workshop then they get prompted a google login

**Comment by VpSnipes** [comment]
This has been a thing for over 6 years, SIX YEARS. This is NOT a phishing tactic, this is/was simply a way for Vrej to notify his users that the base itself was missing through a coded google site he made himself when vj base first started. If this were something malicious (and it isn't) then Vj Base would've been gone long ago. This was an issue discussed AGES ago, sorry buddy but you're about 6 years too late to this.

**Comment by DrVrej** [comment]
Phishing? Lmao, VJ Base is older than you buddy. It was made in a time when custom Google sites were a thing, since then Google has discontinued the service and "upgraded" it. This made notification type of sites like the one used to alert the user that VJ Base is missing against the terms of use. So Google made the website private, now if someone still has a link, it prompts you to sign in, if you sign in, it will simply take you to Google Sites. Since then I have also upgraded the code to use a newer system, however I don't control 99.99% of the VJ addons on the workshop, most authors haven't bothered to upgrade the code thus you are still seeing the old discontinued website link. Next time use your brain cells and do a simple research instead of accusing people of various bullshit. You seriously think one of the top 10 most downloaded mods in GMod has a phishing code in it and no one has noticed for the past 14 years? How egotistical you have to be to assume everyone, including Facepunch hasn't noticed one of the top 10 mods has been running a phishing service for not just a couple years but 14+ years?

**Comment by ZombieWars** [comment]
My mistake then, Anyways I am sorry and really did not mean any disrespect.

**Comment by ZombieWars** [comment]
Also thought you might have been comprised by someone recently, I had no clue about the previous post.

**Comment by DrVrej** [comment]
No worries, no disrespect taken, I appreciate the apology. If you want to help with this issue in any way, I suggest contacting the authors of mods that still use the old code and let them know that a newer version is available. It shouldn't take more than 5 seconds to update 👍

**Comment by ZombieWars** [comment]
> No worries, no disrespect taken, I appreciate the apology. If you want to help with this issue in any way, I suggest contacting the authors of mods that still use the old code and let them know that a newer version is available. It shouldn't take more than 5 seconds to update 👍

https://steamcommunity.com/sharedfiles/filedetails/?id=152529683 this was the only one I needed to work and it still seems very popular today

**Comment by DrVrej** [comment]
> > No worries, no disrespect taken, I appreciate the apology. If you want to help with this issue in any way, I suggest contacting the authors of mods that still use the old code and let them know that a newer version is available. It shouldn't take more than 5 seconds to update 👍
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=152529683 this was the only one I needed to work and it still seems very popular today

Oh that one is a really old mod of mine, I have a full revamp of that mod in work at the moment. Not just an upgrade of this issue, but also a complete revamp of every single NPC. Planning to release it alongside the base revamp coming late this summer. I did a showcase of some of the changes here: https://youtu.be/TfGZdtlaCzE

**Comment by ZombieWars** [comment]
The Zombie Panic Revamp looks amazing!! Definitely would be worth the wait. 

My last question is that am I able to set the npc spawners to automatically spawn npcs even if I restart the server in certain spots of the map?? I watched all the youtube videos and did not see anything about it. I was able to use the perma prop tool on the player spawner entitie but only one for players exist and not npcs in the entities menu.

**Comment by DrVrej** [comment]
No that would be the job of other mods like the one you mentioned, but ones that would work for other entities

**Comment by ZombieWars** [comment]
Thank you, so I would just need to find a vjbase npc mod that has the npc entities so I could perma prop them.

**Comment by ZombieWars** [comment]
nevermind I was able to just Perma prop the NPCS with a timer!!!!

**Comment by ZombieWars** [comment]
nevermind I can perma prop them and have them spawn over and over but when I restart they will spawn but once killed wont respawn
