### ISSUE TITLE
Projectiles using error model despite having model specified

### ISSUE THREAD

**Issue by Bigboibigdum** [DrVrej/VJ-Base#118]
In init.lua: ENT.Model = {"models/hunter/blocks/cube025x025x025.mdl"} -- The models it should spawn with | Picks a random one from the table

In game: 
![image](https://github.com/DrVrej/VJ-Base/assets/87398673/a201814e-c6fe-4ab6-9593-3738032f5f3f)
I've restarted the game twice, no idea why this happens. I've looked at the base's projectile files and this line seems completely fine..
I've also tried other models, including just copy and pasting the code that sets test arial's model but still ERROR

**Comment by DrVrej** [comment]
Please refrain from posting coding help on GitHub as this is a place to report bugs, suggestion, etc. So I suggest reposting this in Discord, forums, or other places. With the lack of info, all I can say is make sure the following: Model exists, no errors in the projectile's code, and no misspelling in the path string

**Comment by Bigboibigdum** [comment]
> > Please refrain from posting coding help on GitHub as this is a place to report bugs, suggestion, etc. So I suggest reposting this in Discord, forums, or other places. With the lack of info, all I can say is make sure the following: Model exists, no errors in the projectile's code, and no misspelling in the path string
> 
> And who are you exactly? Founder and %51+ stakeholder of Github or a fat motherfucker in some basement? Who decides what github is for, stop telling people what to do. But this your repo's page so you can just delete it i guess.

Also, I don't think you should insult the lead developer for trying to keep forums focused.

**Comment by DrVrej** [comment]
> > Please refrain from posting coding help on GitHub as this is a place to report bugs, suggestion, etc. So I suggest reposting this in Discord, forums, or other places. With the lack of info, all I can say is make sure the following: Model exists, no errors in the projectile's code, and no misspelling in the path string
> 
> And who are you exactly? Founder and %51+ stakeholder of Github or a fat motherfucker in some basement? Who decides what github is for, stop telling people what to do. But this your repo's page so you can just delete it i guess.

How's asking a user to refrain from posting coding questions rude? I even said `Please refrain`, none of what I said is rude. Many people make the mistake of asking coding questions here, I always guide them to post on discord or forums. The truth is, you already know it wasn't rude nor is your reply about this post. The simple fact is that you have been following my page waiting for the opportunity to attack me due to your racist mindset. Don't think that I am not aware of why you are doing this, but for the sake of the discussion, I will not continue it further and I suggest you leave users here alone.

**Comment by DrVrej** [comment]
> No need to be so rude, I respect DrVrej for all the gmod modding stuff he's done. But.. I think I'd consider some basic code in a base entity not working as a bug. Also the model here is the default 1x1x1 plastic cube model, just for testing. And I have tried using the exact same code as the aerial test. This is also very early in the projectiles' development, meaning there's no way I could have messed up the code setting the model. And for the misspelling, I've tried both copying the model from the spawnmenu and copying with the entity info tool. Both give the same result.

No worries, he's a racist degenerate who is looking for ways to attack me due to my ethnicity, I am used to it from people like him. As for your question, I suggest joining the Discord server as it's a more dynamic platform, it will allow me and others to help you much easier and quicker 👍

**Comment by Bigboibigdum** [comment]
Alright, where would I find an invite then? I don't think I've ever head of a VJ discord.

**Comment by DrVrej** [comment]
> Alright, where would I find an invite then? I don't think I've ever head of a VJ discord.

Check the description of VJ Base or the VrejGaming group (Steam, YouTube, etc.)

**Comment by Bigboibigdum** [comment]
Ok, thanks!

**Comment by uruskan** [comment]
> > No need to be so rude, I respect DrVrej for all the gmod modding stuff he's done. But.. I think I'd consider some basic code in a base entity not working as a bug. Also the model here is the default 1x1x1 plastic cube model, just for testing. And I have tried using the exact same code as the aerial test. This is also very early in the projectiles' development, meaning there's no way I could have messed up the code setting the model. And for the misspelling, I've tried both copying the model from the spawnmenu and copying with the entity info tool. Both give the same result.
> 
> No worries, he's a racist degenerate who is looking for ways to attack me due to my ethnicity, I am used to it from people like him. As for your question, I suggest joining the Discord server as it's a more dynamic platform, it will allow me and others to help you much easier and quicker 👍

I don't even know your name, skin color, religion or literally anything about you. I just don't like getting notification mails in 1am about what to do and not to do from a guy that i have no idea about. Idk why I was watching this project anyway I hope you find peace and get over the victim mentality.

**Comment by DrVrej** [comment]
> I don't even know your name, skin color, religion or literally anything about you. I just don't like getting notification mails in 1am about what to do and not to do from a guy that i have no idea about. Idk why I was watching this project anyway I hope you find peace and get over the victim mentality.

Sure buddy, you just happen to watch a repository that's related to a game you have never played using a scripting language you have never heard of. Coincidentally you also happen to be part of a group that constantly targets me and other people with similar ethnic background. To top it off, you decide to personally attack me with false claims because I directed a user to another platform. Then you target the other user for because he stated that no one was arguing here. You aren't fooling anyone here, I have dealt with your leftover ex-Mongolic horde all my life. I am very aware of what your destructive hivemind ideologies are and how you target people of certain ethnic backgrounds. Instead of focusing on harming the descendants Anatolia as you are brainwashed to do, you should focus on bettering your life and only then you will find peace.
