### ISSUE TITLE
bug report & suggestions

### ISSUE THREAD

**Issue by Combine900** [DrVrej/VJ-Base#28]
Tested with a clean garrysmod

Mode: SP & MP = Singleplayer, Multiplayer
Mods: Nothing
Map: dev_sdk_gmod
Cheats: On
Activated contents: CSS, DOD, HL2, HL2 DM, HL2 EP1, HL2 EP2, HL2 LC, TF2

Possible fixes
https://wiki.facepunch.com/gmod/Global.PrecacheParticleSystem
roguex100
https://steamcommunity.com/profiles/76561198041335484/myworkshopfiles?appid=4000
Silverlans npc tools
https://steamcommunity.com/sharedfiles/filedetails/?id=104486597

Precache your particle systems correctly, too many to list.
Attemped to precache unknown particle system  "antlion_gib_01"
"vj_rifle_smoke", "vj_bms_turret_muzzle_smoke" etc...

- default hl2 AI keep firing at their targets no matter if they melee attack or their target is behind a wall etc

-Following weapons doesnt drop any shells, even if "Disable Bullet shells" is not checked.
weapon_vj_9mmpistol, weapon_vj_glock17, weapon_vj_mp40, weapon_vj_smg1, weapon_vj_spas12

Update npc translation for this weapons that metropolice & combine solders can use it. (roguex100 made a almost perfect ai weapon translation)
weapon_vj_357, weapon_vj_9mmpistol, weapon_vj_flaregun, weapon_vj_glock17, weapon_vj_m16a1, weapon_vj_rpg, weapon_vj_spas12, "VJ_SSG-08" "VJ_crowbar"

- "VJ_crowbar" creates lua errors if a AI try to use it.
Timer Failed! [Simple][@lua/weapons/weapon_vj_base/shared.lua (line 462)]
[VJ Base] lua/weapons/weapon_vj_base/shared.lua:553: attempt to call method 'CustomOnMeleeAttack_Miss' (a nil value)
  1. PrimaryAttack - lua/weapons/weapon_vj_base/shared.lua:553
   2. unknown - lua/weapons/weapon_vj_base/shared.lua:464

REQUESTS:
- May add a cooldown for AI that use "weapon_vj_flaregun"
- Make only admins can spawn "sent_vj_test"
- Maybe disable the secondary ammo on hud for VJ weapons
- Add killicons for every VJ weapon
- May add new spawnicons the current look ugly lol
- May improve your npcs tools by taking a look at silverlans
- Can we get a extra tab for the VJ AI weapons?

**Comment by DrVrej** [comment]
In order:
- Particle precache error, ignore it, that happens with any particle in the game, though I wish the GMod devs would just disable that message to not confuse people.
- The NPC weapons, especially the melee are mostly made for VJ Human SNPCs, though guns do have some support for HL2. With HLR you won't really need to use HL2 humans anymore, since it remakes all of them on VJ Base.
- Error fixed, this bug only exists with HL2 NPCs, VJ NPCs work 100%, I would have to spend considerable amount of time to add proper support for something I won't ever use, I have completely stopped using HL2 NPCs since the creation of HLR. So for melee weapons, don't use them at all with HL2 NPCs, it won't work.

REQUESTS:
- Works fine on VJ Humans, but as some of the other issues, doesn't work well with HL2 NPCs.
- "sent_vj_test" is now admin only.
- Fixed this bug, HUDs no longer think there is a secondary attack.
- I'll see what I can do about this, I don't really make any textures so I don't know how I will be able to get kill icons unless someone makes them for me.
- If you mean the weapon spawnicons, this was debated before, some liked the meme icons and some wanted it to change ¯\_(ツ)_/¯
- Going to have to be more specific then that lol
- This was also debated before, I might include it in the future.

**Comment by AKLFR** [comment]
Hello, I noticed that the NPCs precisely: https://steamcommunity.com/sharedfiles/filedetails/?id=221942657
have a problem, the bodies of the destroyed NPCs do not disappear despite the configuration indicated.

**Comment by DrVrej** [comment]
> Hello, I noticed that the NPCs precisely: https://steamcommunity.com/sharedfiles/filedetails/?id=221942657
> have a problem, the bodies of the destroyed NPCs do not disappear despite the configuration indicated.

You are posting this on the wrong ticket, but to answer your question: This isn't a bug, you either have a conflicting mod or you are trying to use the menu on a dedicated server.

**Comment by Crazygibus** [comment]
what is the version of vj base that supports gmod 14?

**Comment by Crazygibus** [comment]
I downloaded Half Life Resurgence

**Comment by lazypersonandlazyname-zip** [comment]
Suggestion: Arctic's Customizable Weapons (weapon base) compatibility.
basically, compatibility with arccw.

**Comment by DrVrej** [comment]
The last remaining feature from the suggestion list has been added and will be included in the next VJ Base update 👍
The be exact, the feature adds a unique weapon selection specifically for VJ NPC weapons only, this selection will be included under the VJ Base spawn menu.
